name: google_signin_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  cloud_firestore: ^0.16.0
  flutter_map: ^0.11.0
  firebase_auth: ^0.20.0+1
  google_sign_in: ^4.5.9
  flutter_barcode_scanner: ^1.0.1
  provider: ^4.3.2+2
  font_awesome_flutter: ^8.10.0
  geolocation: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

